### PR TITLE
Moved bluebird dependency from devDependencies to dependencies.

### PR DESCRIPTION
**Pull request by jonathansamines**
This will fix a little error when created the dual api in my previous pull request.

### CODE REVIEW

**Comment by andreareginato** [comment]
@jonathansamines are there some problems about this pull request that hasn't been merged?

**Comment by jonathansamines** [comment]
@andreareginato not in code at all, it´s only that i added bluebird (the promises library) as a devDependency, which is wrong. It has to be a dependency. I just forgot to merge it to master.

**Comment by jonathansamines** [comment]
@andreareginato also, i was thinking on make a new release with the promise based API to NPM, but as i know i don´t have access to publish to npm, could you publish it?

**Comment by andreareginato** [comment]
@jonathansamines I think would be great if you could follow all the steps, including the NPM publishing. Would you like to do it?

**Comment by jonathansamines** [comment]
@andreareginato of course, i have no problems with that. I really need to use the promise api on one of my projects, so i really need those changes to be in npm! :grinning:

**Comment by andreareginato** [comment]
You are now a collaborator for the NPM repo. You should be able to create the new package.
If possible keep the history updated for future users.

**Comment by jonathansamines** [comment]
Thanks, i´ll work on creating a new release in this days.

**Pull request merged**
